# generated by fastapi-codegen:
#   filename:  pet.yaml
#   timestamp: 2024-11-07T17:47:37+00:00

from __future__ import annotations

from typing import List, Optional, Union

from fastapi import FastAPI, Path
from pydantic import conint

from models import Error, Pet

app = FastAPI(
    version='1.0.0',
    title='Swagger хранилище питомцев',
    license={'name': 'MIT'},
    servers=[{'url': 'http://127.0.0.1:8000/'}, {'url': 'http://api.myserver.ru/v1'}],
)

pets_dict = {"0": Pet(id = 0, name = "dog")}

@app.get(
    '/pets',
    response_model=List[Pet],
    responses={'default': {'model': Error}},
    tags=['pets'],
)
def list_pets(limit: Optional[conint(le=100)] = None) -> Union[List[Pet], Error]:
    """
    список всех питомцев
    """
    return list(pets_dict.values())


@app.post(
    '/pets', response_model=None, responses={'default': {'model': Error}}, tags=['pets']
)
def create_pets(body: Pet) -> Optional[Error]:
    """
    Создание питомца
    """
    id = len(pets_dict) + 1
    new_pet = Pet(id = id, name = f"New pet #{id}")
    pets_dict[id] = new_pet
    return {"result": id}


@app.get(
    '/pets/{petId}',
    response_model=Union[Pet, Error],
    responses={'default': {'model': Error}},
    tags=['pets'],
)
def show_pet_by_id(pet_id: str = Path(..., alias='petId')) -> Union[Pet, Error]:
    """
    Информация о питомце
    """
    if pets_dict.get(pet_id) is not None:
        return pets_dict[pet_id]
    return Error(code = 0, message = f"Нету челика №{pet_id}")
