# generated by fastapi-codegen:
#   filename:  C:\Users\Normist\Desktop\Учёба\IIS\2\pet.yaml
#   timestamp: 2024-11-07T17:47:37+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class Pet(BaseModel):
    id: int
    name: str
    tag: Optional[str] = None


class Error(BaseModel):
    code: int
    message: str
